from app.repositories.order_repository import OrderRepository
from app.models.order import Order
from app.models.delivery_info import DeliveryInfo
from app.utils.geo_utils import calculate_distance # Use the file provided in previous answer
from app.repositories.payment_repository import PaymentRepository
from datetime import datetime, timedelta, time
# Config
MUNCHEEZ_LAT = 24.8607 
MUNCHEEZ_LNG = 67.0011
MAX_DISTANCE_KM = 10.0

class OrderService:
    @staticmethod
    def create_initial_order(customer_id, total_amount):
        # Create object (ID is auto-generated by DB)
        new_order = Order(
            customer_id=customer_id, 
            total_amount=total_amount, 
            status="pending"
        )
        return OrderRepository.create(new_order)

    @staticmethod
    def validate_and_add_location(order_id, address, lat, lng):
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")

        # 1. Logic: Check Distance
        distance = calculate_distance(MUNCHEEZ_LAT, MUNCHEEZ_LNG, lat, lng)
        is_allowed = distance <= MAX_DISTANCE_KM

        # 2. Logic: Create Delivery Object
        delivery_info = DeliveryInfo(
            order_id=order_id, # Linking to order
            address=address,
            latitude=lat,
            longitude=lng,
            is_within_range=is_allowed
        )

        OrderRepository.add_delivery_info(delivery_info)

        if not is_allowed:
            raise ValueError(f"Too far! You are {distance:.2f}km away. Limit is {MAX_DISTANCE_KM}km.")

    @staticmethod
    def update_order(order_id, data):
        """
        General method to update order fields (status, total_amount, etc.)
        """
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")

        # Update status if provided
        if 'status' in data:
            valid_statuses = ['pending', 'location_verified', 'awaiting_approval', 'paid', 'accepted', 'preparing', 'completed', 'rejected']
            if data['status'] not in valid_statuses:
                raise ValueError(f"Invalid status. Must be one of: {', '.join(valid_statuses)}")
            order.status = data['status']

        # Update total_amount if provided
        if 'total_amount' in data:
            order.total_amount = float(data['total_amount'])

        # Save to DB
        OrderRepository.update_status(order, order.status)
        
        return {
            "message": "Order updated successfully",
            "order_id": order_id,
            "order": order.to_dict()
        }

    @staticmethod
    def update_order_status(order_id, action):
        """
        Handles Admin review actions: 'approve' or 'reject'
        """
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")

        if action == "approve":
            # Change status to accepted/preparing
            new_status = "accepted"
        elif action == "reject":
            # Soft delete (mark as rejected)
            new_status = "rejected"
        else:
            raise ValueError(f"Invalid action: {action}")

        # Save to DB
        OrderRepository.update_status(order, new_status)
        
        return {
            "message": f"Order {action}d successfully", 
            "status": new_status,
            "order_id": order_id
        }
        

    @staticmethod
    def get_order_details(order_id):
        """Get full order details including delivery info and payment"""
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")
        
        # Get delivery info
        delivery_info = None
        if order.delivery_info:
            delivery_info = {
                "address": order.delivery_info.address,
                "latitude": order.delivery_info.latitude,
                "longitude": order.delivery_info.longitude,
                "is_within_range": order.delivery_info.is_within_range
            }
        
        # Get payment info
        payment_info = None
        if order.payment:
            payment_info = {
                "method": order.payment.method,
                "amount": float(order.payment.amount),
                "screenshot_url": order.payment.screenshot_url,
                "payment_date": order.payment.payment_date.isoformat() if order.payment.payment_date else None
            }
        
        # Get customer info
        customer_info = None
        if order.customer:
            customer_info = {
                "user_id": order.customer.user_id,
                "name": order.customer.name,
                "phone": order.customer.phone,
                "address": order.customer.address
            }
        
        return {
            "order_id": order.order_id,
            "customer_id": order.customer_id,
            "status": order.status,
            "total_amount": float(order.total_amount),
            "created_at": order.created_at.isoformat() if order.created_at else None,
            "customer": customer_info,
            "delivery_info": delivery_info,
            "payment": payment_info
        }

    @staticmethod
    def get_all_orders(status=None):
        """Get all orders, optionally filtered by status"""
        from app.models.order import Order
        if status:
            orders = Order.query.filter_by(status=status).order_by(Order.created_at.desc()).all()
        else:
            orders = Order.query.order_by(Order.created_at.desc()).all()
        return orders

    @staticmethod
    def get_customer_orders(customer_id):
        """Get all orders for a specific customer"""
        from app.models.order import Order
        orders = Order.query.filter_by(customer_id=customer_id).order_by(Order.created_at.desc()).all()
        return orders

    @staticmethod
    def get_analytics(report_type):
        now = datetime.utcnow()
        
        if report_type == 'daily':
            # Range: Today 00:00:00 to 23:59:59
            start_date = datetime.combine(now.date(), time.min)
            end_date = datetime.combine(now.date(), time.max)
            
            # For daily, we just want the total number, not a graph
            total = PaymentRepository.get_total_sum(start_date, end_date)
            return {
                "type": "daily",
                "date": str(now.date()),
                "total_sales": total
            }

        elif report_type == 'monthly':
            # Range: 1st of this month to Now
            start_date = now.replace(day=1, hour=0, minute=0, second=0)
            end_date = now
            
            # Get data grouped by DAY (for the graph)
            results = PaymentRepository.get_sales_stats(start_date, end_date, 'day')
            
            # Format data for Frontend Graph
            graph_data = []
            for r in results:
                graph_data.append({
                    "date": r.period.strftime("%Y-%m-%d"), # Label: "2023-11-25"
                    "sales": float(r.total_sales),         # Y-Axis: 1500.0
                    "count": r.tx_count
                })
                
            total = sum(item['sales'] for item in graph_data)
            
            return {
                "type": "monthly",
                "month": now.strftime("%B"),
                "total_sales": total,
                "graph_data": graph_data
            }

        elif report_type == 'yearly':
            # Range: Jan 1st of this year to Now
            start_date = now.replace(month=1, day=1, hour=0, minute=0, second=0)
            end_date = now
            
            # Get data grouped by MONTH (for the graph)
            results = PaymentRepository.get_sales_stats(start_date, end_date, 'month')
            
            graph_data = []
            for r in results:
                graph_data.append({
                    "month": r.period.strftime("%B"), # Label: "November"
                    "sales": float(r.total_sales),
                    "count": r.tx_count
                })
                
            total = sum(item['sales'] for item in graph_data)
            
            return {
                "type": "yearly",
                "year": now.year,
                "total_sales": total,
                "graph_data": graph_data
            }