from app.repositories.order_repository import OrderRepository
from app.models.order import Order
from app.models.order_item import OrderItem
from app.models.delivery_info import DeliveryInfo
from app.utils.geo_utils import calculate_distance # Use the file provided in previous answer
from app.repositories.payment_repository import PaymentRepository
from app.extensions import db
from datetime import datetime, timedelta, time
# Config
MUNCHEEZ_LAT = 24.8607 
MUNCHEEZ_LNG = 67.0011
MAX_DISTANCE_KM = 10.0

class OrderService:
    @staticmethod
    def create_initial_order(customer_id, total_amount, items=None):
        # Create object (ID is auto-generated by DB)
        new_order = Order(
            customer_id=customer_id, 
            total_amount=total_amount, 
            status="pending"
        )
        order = OrderRepository.create(new_order)
        
        # Add order items if provided
        if items:
            OrderService.add_order_items(order.order_id, items)
        
        return order
    
    @staticmethod
    def add_order_items(order_id, items):
        """Add items to an order"""
        from app.models.product import ProductItem
        
        for item_data in items:
            item_id = item_data.get('item_id')
            quantity = item_data.get('quantity', 1)
            price = item_data.get('price')
            
            # If price not provided, get it from product item
            if price is None:
                product_item = ProductItem.query.get(item_id)
                if product_item:
                    price = float(product_item.price)
                else:
                    raise ValueError(f"Product item {item_id} not found")
            
            order_item = OrderItem(
                order_id=order_id,
                item_id=item_id,
                quantity=quantity,
                price=price
            )
            db.session.add(order_item)
        
        db.session.commit()

    @staticmethod
    def validate_and_add_location(order_id, address, lat, lng):
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")

        # 1. Logic: Check Distance
        distance = calculate_distance(MUNCHEEZ_LAT, MUNCHEEZ_LNG, lat, lng)
        is_allowed = distance <= MAX_DISTANCE_KM

        # 2. Logic: Create Delivery Object
        delivery_info = DeliveryInfo(
            order_id=order_id, # Linking to order
            address=address,
            latitude=lat,
            longitude=lng,
            is_within_range=is_allowed
        )

        OrderRepository.add_delivery_info(delivery_info)

        if not is_allowed:
            raise ValueError(f"Too far! You are {distance:.2f}km away. Limit is {MAX_DISTANCE_KM}km.")

    @staticmethod
    def update_order(order_id, data):
        """
        General method to update order fields (status, total_amount, etc.)
        """
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")

        # Update status if provided
        if 'status' in data:
            valid_statuses = ['pending', 'location_verified', 'awaiting_approval', 'paid', 'accepted', 'preparing', 'completed', 'rejected']
            if data['status'] not in valid_statuses:
                raise ValueError(f"Invalid status. Must be one of: {', '.join(valid_statuses)}")
            order.status = data['status']

        # Update total_amount if provided
        if 'total_amount' in data:
            order.total_amount = float(data['total_amount'])

        # Save to DB
        OrderRepository.update_status(order, order.status)
        
        return {
            "message": "Order updated successfully",
            "order_id": order_id,
            "order": order.to_dict()
        }

    @staticmethod
    def update_order_status(order_id, action):
        """
        Handles Admin review actions: 'approve', 'reject', or 'completed'
        """
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")

        if action == "approve":
            # Change status to accepted
            new_status = "accepted"
        elif action == "reject":
            # Mark as rejected
            new_status = "rejected"
        elif action == "completed":
            # Mark as completed
            new_status = "completed"
        else:
            raise ValueError(f"Invalid action: {action}. Must be 'approve', 'reject', or 'completed'")

        # Save to DB
        OrderRepository.update_status(order, new_status)
        
        return {
            "message": f"Order {action}d successfully", 
            "status": new_status,
            "order_id": order_id
        }
        

    @staticmethod
    def get_order_details(order_id):
        """Get full order details including delivery info, payment, and items"""
        order = OrderRepository.get_by_id(order_id)
        if not order:
            raise ValueError("Order not found")
        
        # Use the Order model's to_dict method which includes items
        return order.to_dict()

    @staticmethod
    def get_all_orders(status=None):
        """Get all orders, optionally filtered by status"""
        from app.models.order import Order
        if status:
            orders = Order.query.filter_by(status=status).order_by(Order.created_at.desc()).all()
        else:
            orders = Order.query.order_by(Order.created_at.desc()).all()
        return orders

    @staticmethod
    def get_customer_orders(customer_id):
        """Get all orders for a specific customer"""
        from app.models.order import Order
        orders = Order.query.filter_by(customer_id=customer_id).order_by(Order.created_at.desc()).all()
        return orders

    @staticmethod
    def get_analytics(report_type):
        now = datetime.utcnow()
        
        if report_type == 'daily':
            # Range: Today 00:00:00 to 23:59:59
            start_date = datetime.combine(now.date(), time.min)
            end_date = datetime.combine(now.date(), time.max)
            
            # For daily, we just want the total number, not a graph
            total = PaymentRepository.get_total_sum(start_date, end_date)
            return {
                "type": "daily",
                "date": str(now.date()),
                "total_sales": total
            }

        elif report_type == 'monthly':
            # Range: 1st of this month to Now
            start_date = now.replace(day=1, hour=0, minute=0, second=0)
            end_date = now
            
            # Get data grouped by DAY (for the graph)
            results = PaymentRepository.get_sales_stats(start_date, end_date, 'day')
            
            # Format data for Frontend Graph
            graph_data = []
            for r in results:
                graph_data.append({
                    "date": r.period.strftime("%Y-%m-%d"), # Label: "2023-11-25"
                    "sales": float(r.total_sales),         # Y-Axis: 1500.0
                    "count": r.tx_count
                })
                
            total = sum(item['sales'] for item in graph_data)
            
            return {
                "type": "monthly",
                "month": now.strftime("%B"),
                "total_sales": total,
                "graph_data": graph_data
            }

        elif report_type == 'yearly':
            # Range: Jan 1st of this year to Now
            start_date = now.replace(month=1, day=1, hour=0, minute=0, second=0)
            end_date = now
            
            # Get data grouped by MONTH (for the graph)
            results = PaymentRepository.get_sales_stats(start_date, end_date, 'month')
            
            graph_data = []
            for r in results:
                graph_data.append({
                    "month": r.period.strftime("%B"), # Label: "November"
                    "sales": float(r.total_sales),
                    "count": r.tx_count
                })
                
            total = sum(item['sales'] for item in graph_data)
            
            return {
                "type": "yearly",
                "year": now.year,
                "total_sales": total,
                "graph_data": graph_data
            }

    @staticmethod
    def get_dashboard_stats():
        """
        Get dashboard statistics: daily sales, weekly revenue, and chart data
        """
        from app.models.order import Order
        from app.repositories.payment_repository import PaymentRepository
        from datetime import timedelta
        
        now = datetime.utcnow()
        today = datetime.combine(now.date(), time.min)
        today_end = datetime.combine(now.date(), time.max)
        
        # Get today's sales (from payments)
        today_sales = PaymentRepository.get_total_sum(today, today_end)
        
        # Get last week's revenue (7 days ago to today)
        week_start = today - timedelta(days=7)
        last_week_revenue = PaymentRepository.get_total_sum(week_start, today_end)
        
        # Get last 30 days of daily data for chart
        thirty_days_ago = today - timedelta(days=30)
        daily_results = PaymentRepository.get_sales_stats(thirty_days_ago, today_end, 'day')
        
        daily_data = []
        for r in daily_results:
            daily_data.append({
                "date": r.period.strftime("%Y-%m-%d"),
                "sales": float(r.total_sales) if r.total_sales else 0
            })
        
        # Get last 12 weeks of weekly data
        twelve_weeks_ago = today - timedelta(weeks=12)
        # Group daily data into weeks
        weekly_data = []
        current_week_start = twelve_weeks_ago
        while current_week_start < today_end:
            week_end = min(current_week_start + timedelta(days=7), today_end)
            week_sales = PaymentRepository.get_total_sum(current_week_start, week_end)
            weekly_data.append({
                "label": current_week_start.strftime("%Y-%m-%d"),
                "sales": float(week_sales) if week_sales else 0
            })
            current_week_start = week_end
        
        # Get last 12 months of monthly data
        twelve_months_ago = now.replace(day=1) - timedelta(days=365)
        monthly_results = PaymentRepository.get_sales_stats(twelve_months_ago, today_end, 'month')
        
        monthly_data = []
        for r in monthly_results:
            monthly_data.append({
                "label": r.period.strftime("%b"),
                "sales": float(r.total_sales) if r.total_sales else 0
            })
        
        # Get last 12 days sales for mini chart
        last_12_days = []
        for i in range(12):
            day = today - timedelta(days=11-i)
            day_end = day + timedelta(days=1)
            day_sales = PaymentRepository.get_total_sum(day, day_end)
            last_12_days.append(float(day_sales) if day_sales else 0)
        
        # Get last 12 weeks sales for mini chart
        last_12_weeks = weekly_data[-12:] if len(weekly_data) >= 12 else weekly_data
        last_12_weeks_sales = [w["sales"] for w in last_12_weeks]
        
        return {
            "today_sales": float(today_sales) if today_sales else 0,
            "last_week_revenue": float(last_week_revenue) if last_week_revenue else 0,
            "daily_data": daily_data[-30:] if len(daily_data) > 30 else daily_data,  # Last 30 days
            "weekly_data": weekly_data[-12:] if len(weekly_data) > 12 else weekly_data,  # Last 12 weeks
            "monthly_data": monthly_data[-12:] if len(monthly_data) > 12 else monthly_data,  # Last 12 months
            "last_12_days_sales": last_12_days,
            "last_12_weeks_sales": last_12_weeks_sales
        }

    @staticmethod
    def get_reports_data(start_date=None, end_date=None):
        """
        Get reports data: accepted/rejected stats, trend data, and orders list
        """
        from app.models.order import Order
        from datetime import timedelta
        
        now = datetime.utcnow()
        
        # Default to last 12 months if dates not provided
        if not start_date:
            start_date = (now - timedelta(days=365)).strftime("%Y-%m-%d")
        if not end_date:
            end_date = now.strftime("%Y-%m-%d")
        
        start_dt = datetime.strptime(start_date, "%Y-%m-%d")
        end_dt = datetime.strptime(end_date, "%Y-%m-%d") + timedelta(days=1)  # Include end date
        
        # Get all orders in date range (including all statuses: completed, rejected, accepted, etc.)
        orders = Order.query.filter(
            Order.created_at >= start_dt,
            Order.created_at <= end_dt
        ).order_by(Order.created_at.desc()).all()
        # Calculate accepted/rejected counts
        accepted_count = sum(1 for o in orders if o.status == 'accepted' or o.status == 'completed')
        rejected_count = sum(1 for o in orders if o.status == 'rejected')
        total_count = len(orders)
        
        # Calculate percentages
        accepted_percentage = int((accepted_count / total_count * 100)) if total_count > 0 else 0
        rejected_percentage = int((rejected_count / total_count * 100)) if total_count > 0 else 0
        
        # Get monthly trend data for accepted and rejected
        monthly_trend = []
        current = start_dt.replace(day=1)
        
        while current < end_dt:
            month_start = current
            # Calculate end of month
            if current.month == 12:
                month_end = current.replace(year=current.year + 1, month=1, day=1) - timedelta(days=1)
            else:
                month_end = current.replace(month=current.month + 1, day=1) - timedelta(days=1)
            
            if month_end > end_dt:
                month_end = end_dt
            
            month_key = current.strftime("%b").upper()
            
            month_orders = Order.query.filter(
                Order.created_at >= month_start,
                Order.created_at <= month_end
            ).all()
            
            accepted_value = sum(float(o.total_amount) for o in month_orders if o.status in ['accepted', 'completed'])
            rejected_value = sum(float(o.total_amount) for o in month_orders if o.status == 'rejected')
            
            monthly_trend.append({
                "date": current,
                "month": month_key,
                "accepted": accepted_value,
                "rejected": rejected_value
            })
            
            # Move to next month
            if current.month == 12:
                current = current.replace(year=current.year + 1, month=1)
            else:
                current = current.replace(month=current.month + 1)
        
        # Sort by date and format trend data for frontend
        monthly_trend.sort(key=lambda x: x["date"])
        
        trend_data = {
            "accepted": [{"month": m["month"], "value": m["accepted"]} for m in monthly_trend],
            "rejected": [{"month": m["month"], "value": m["rejected"]} for m in monthly_trend]
        }
        
        # Get orders list with customer info - include all statuses (completed, rejected, accepted, etc.)
        # Sort by created_at descending to get most recent first
        sorted_orders = sorted(orders, key=lambda o: o.created_at if o.created_at else datetime.min, reverse=True)
        
        orders_list = []
        for order in sorted_orders[:50]:  # Limit to 50 most recent
            customer_name = order.customer.name if order.customer else "Unknown"
            customer_phone = order.customer.phone if order.customer else "N/A"
            
            orders_list.append({
                "id": f"#{order.order_id}",
                "customerName": customer_name,
                "phone": customer_phone,
                "orderDate": order.created_at.strftime("%d. %m. %Y") if order.created_at else "N/A",
                "total": f"Rs{float(order.total_amount):.2f}"
            })
        
        return {
            "chartData": {
                "accepted": accepted_percentage,
                "rejected": rejected_percentage
            },
            "trendData": trend_data,
            "orders": orders_list
        }