"""add_image_url_to_product_items

Revision ID: 1e8185993b73
Revises: 0b1c08a25a92
Create Date: 2025-12-07 11:47:20.109151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8185993b73'
down_revision = '0b1c08a25a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_items', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
