"""add_status_updated_at_to_orders

Revision ID: 221df8cfbe39
Revises: 5d9ac2a6ebfb
Create Date: 2025-12-08 00:02:41.219220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221df8cfbe39'
down_revision = '5d9ac2a6ebfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status_updated_at')

    # ### end Alembic commands ###
